"""add_incomes_tables

Revision ID: 0734b2400886
Revises: a67553199485
Create Date: 2026-07-20 10:43:09.921007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0734b2400886'
down_revision: Union[str, Sequence[str], None] = 'a67553199485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True),
    sa.Column('card_network', sa.String(length=20), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('available_credit', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_totals', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_credit_card_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_credit_card_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_card'))
    )
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_card_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_card_user_id'), ['user_id'], unique=False)

    op.create_table('expense_service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('last_paid_at', sa.Date(), nullable=True),
    sa.Column('last_paid_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_create_expense', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_expense_service_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expense_service_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_service'))
    )
    with op.batch_alter_table('expense_service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_service_user_id'), ['user_id'], unique=False)

    op.create_table('income_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('income_type', sa.String(length=20), nullable=False),
    sa.Column('stability', sa.String(length=20), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('default_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('default_account_id', sa.UUID(), nullable=True),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('pay_day', sa.Integer(), nullable=True),
    sa.Column('total_received', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('income_count', sa.Integer(), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_account_id'], ['financial_account.id'], name=op.f('fk_income_source_default_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_category_id'], ['category.id'], name=op.f('fk_income_source_default_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_income_source_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_source'))
    )
    with op.batch_alter_table('income_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_source_user_id'), ['user_id'], unique=False)

    op.create_table('credit_card_bill',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('interest_charged', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_card.id'], name=op.f('fk_credit_card_bill_credit_card_id_credit_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_credit_card_bill_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_card_bill'))
    )
    with op.batch_alter_table('credit_card_bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_card_bill_credit_card_id'), ['credit_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_card_bill_user_id'), ['user_id'], unique=False)

    op.create_table('expense_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_account_id', sa.UUID(), nullable=True),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('default_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('default_notes', sa.Text(), nullable=True),
    sa.Column('default_source', sa.String(length=20), nullable=False),
    sa.Column('default_frequency', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_account_id'], ['financial_account.id'], name=op.f('fk_expense_template_default_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_category_id'], ['category.id'], name=op.f('fk_expense_template_default_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_subcategory_id'], ['subcategory.id'], name=op.f('fk_expense_template_default_subcategory_id_subcategory'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expense_template_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_template'))
    )
    with op.batch_alter_table('expense_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_template_user_id'), ['user_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('billing_frequency', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('cancelled_date', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('linked_recurring_id', sa.UUID(), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('annual_cost', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('annual_cost_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_subscription_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_subscription_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_recurring_id'], ['transaction_recurring.id'], name=op.f('fk_subscription_linked_recurring_id_transaction_recurring'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_subscription_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('income',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('income_type', sa.String(length=20), nullable=False),
    sa.Column('income_status', sa.String(length=20), nullable=False),
    sa.Column('stability', sa.String(length=20), nullable=False),
    sa.Column('income_source_id', sa.UUID(), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('employer_tax_id', sa.String(length=50), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('tax_withheld', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_source.id'], name=op.f('fk_income_income_source_id_income_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_income_transaction_id_transaction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_income_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income'))
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_income_source_id'), ['income_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_income_user_id'), ['user_id'], unique=False)

    op.create_table('income_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('income_source_id', sa.UUID(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('projection_method', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_transaction_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_income_schedule_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_source.id'], name=op.f('fk_income_schedule_income_source_id_income_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_transaction_id'], ['transaction.id'], name=op.f('fk_income_schedule_received_transaction_id_transaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_income_schedule_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_schedule'))
    )
    with op.batch_alter_table('income_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_schedule_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_schedule_expected_date'), ['expected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_schedule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_schedule_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_schedule_expected_date'))
        batch_op.drop_index(batch_op.f('ix_income_schedule_account_id'))

    op.drop_table('income_schedule')
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_income_income_source_id'))

    op.drop_table('income')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('expense_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_template_user_id'))

    op.drop_table('expense_template')
    with op.batch_alter_table('credit_card_bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_card_bill_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_card_bill_credit_card_id'))

    op.drop_table('credit_card_bill')
    with op.batch_alter_table('income_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_source_user_id'))

    op.drop_table('income_source')
    with op.batch_alter_table('expense_service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_service_user_id'))

    op.drop_table('expense_service')
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_card_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_card_account_id'))

    op.drop_table('credit_card')
    # ### end Alembic commands ###
