"""add_user_profiles_and_preferences

Revision ID: 28e8f29983b9
Revises: 2cd01c1c674b
Create Date: 2026-07-19 13:19:23.786816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28e8f29983b9"
down_revision: str | Sequence[str] | None = "2cd01c1c674b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean orphaned enum types
    op.execute("DROP TYPE IF EXISTS user_gender CASCADE")
    op.execute("DROP TYPE IF EXISTS time_format_type CASCADE")
    op.execute("DROP TYPE IF EXISTS week_start_type CASCADE")
    op.execute("DROP TYPE IF EXISTS theme_type CASCADE")

    # Create tables (autogenerated)
    op.create_table(
        "user_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", "prefer_not_to_say", name="user_gender"),
            nullable=True,
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("phone_secondary", sa.String(length=50), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_profile_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile")),
    )
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_profile_user_id"), ["user_id"], unique=True)

    op.create_table(
        "user_preference",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("date_format", sa.String(length=20), nullable=False),
        sa.Column("time_format", sa.Enum("12h", "24h", name="time_format_type"), nullable=False),
        sa.Column("number_format", sa.String(length=30), nullable=False),
        sa.Column(
            "first_day_of_week", sa.Enum("monday", "sunday", name="week_start_type"), nullable=False
        ),
        sa.Column("theme", sa.Enum("light", "dark", "system", name="theme_type"), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("push_notifications", sa.Boolean(), nullable=False),
        sa.Column("marketing_emails", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_preference_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preference")),
    )
    with op.batch_alter_table("user_preference", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_preference_user_id"), ["user_id"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("user_preference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_preference_user_id"))
    op.drop_table("user_preference")

    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_profile_user_id"))
    op.drop_table("user_profile")

    sa.Enum(name="theme_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="week_start_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="time_format_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="user_gender").drop(op.get_bind(), checkfirst=True)
