"""add_loan_tables

Revision ID: 414b44a94f2c
Revises: 663e62c216eb
Create Date: 2026-07-21 08:13:39.982579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '414b44a94f2c'
down_revision: Union[str, Sequence[str], None] = '663e62c216eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('loan_type', sa.Enum('personal', 'mortgage', 'auto', 'student', 'business', 'personal_line', 'payday', 'microloan', 'consolidation', name='loan_type_enum'), nullable=False),
    sa.Column('lender_name', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('interest_type', sa.Enum('fixed', 'variable', 'mixed', name='interest_type_enum'), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('monthly', 'bi_weekly', 'weekly', name='payment_frequency_enum'), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_interest_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_interest_expected', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('first_payment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('final_payment_date', sa.Date(), nullable=True),
    sa.Column('paid_off_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'paid_off', 'defaulted', 'refinanced', 'suspended', 'cancelled', name='loan_status_enum'), nullable=False),
    sa.Column('penalty_rate_monthly', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('early_payoff_allowed', sa.Boolean(), nullable=False),
    sa.Column('early_payoff_penalty_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_loan_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_loan_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan'))
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_loan_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_loan_user_type', ['user_id', 'loan_type'], unique=False)

    op.create_table('loan_amortization_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('entry_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_interest_to_date', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_principal_to_date', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], name=op.f('fk_loan_amortization_entry_loan_id_loan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_amortization_entry'))
    )
    with op.batch_alter_table('loan_amortization_entry', schema=None) as batch_op:
        batch_op.create_index('ix_amortization_loan_number', ['loan_id', 'entry_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_loan_amortization_entry_loan_id'), ['loan_id'], unique=False)

    op.create_table('loan_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('penalty_portion', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('bank_transfer', 'cash', 'auto_debit', 'check', 'online', 'mobile', name='loan_payment_method_enum'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'reversed', name='loan_payment_status_enum'), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_extra_payment', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], name=op.f('fk_loan_payment_loan_id_loan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_payment'))
    )
    with op.batch_alter_table('loan_payment', schema=None) as batch_op:
        batch_op.create_index('ix_loan_payment_date', ['loan_id', 'payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_payment_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_payment_loan_id'))
        batch_op.drop_index('ix_loan_payment_date')

    op.drop_table('loan_payment')
    with op.batch_alter_table('loan_amortization_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_amortization_entry_loan_id'))
        batch_op.drop_index('ix_amortization_loan_number')

    op.drop_table('loan_amortization_entry')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_user_type')
        batch_op.drop_index('ix_loan_user_status')
        batch_op.drop_index(batch_op.f('ix_loan_user_id'))

    op.drop_table('loan')
    # ### end Alembic commands ###
