"""add_automation_tables

Revision ID: 56f13aaab89f
Revises: 6a2da3f1440a
Create Date: 2026-07-21 13:48:23.567507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56f13aaab89f'
down_revision: Union[str, Sequence[str], None] = '6a2da3f1440a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_executions_per_month', sa.Integer(), nullable=True),
    sa.Column('min_balance_required', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_automation_rule_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rule'))
    )
    with op.batch_alter_table('automation_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rule_user_id'), ['user_id'], unique=False)

    op.create_table('automation_execution_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('amount_involved', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('target_account_id', sa.UUID(), nullable=True),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rule.id'], name=op.f('fk_automation_execution_log_rule_id_automation_rule'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_automation_execution_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_execution_log'))
    )
    with op.batch_alter_table('automation_execution_log', schema=None) as batch_op:
        batch_op.create_index('ix_auto_exec_log_rule', ['rule_id', 'executed_at'], unique=False)
        batch_op.create_index('ix_auto_exec_log_user', ['user_id', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_execution_log_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_execution_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_execution_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_execution_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_automation_execution_log_rule_id'))
        batch_op.drop_index('ix_auto_exec_log_user')
        batch_op.drop_index('ix_auto_exec_log_rule')

    op.drop_table('automation_execution_log')
    with op.batch_alter_table('automation_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rule_user_id'))

    op.drop_table('automation_rule')
    # ### end Alembic commands ###
