"""add_budgets_tables

Revision ID: 5fbda53170bf
Revises: 0734b2400886
Create Date: 2026-07-20 14:33:35.555297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fbda53170bf'
down_revision: Union[str, Sequence[str], None] = '0734b2400886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('spent', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('remaining', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_adjust', sa.Boolean(), nullable=False),
    sa.Column('adjustment_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('rollover_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('strategy', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_budget_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_budget_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_budget_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_user_id'), ['user_id'], unique=False)

    op.create_table('budget_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('fk_budget_alert_budget_id_budget'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_budget_alert_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_alert'))
    )
    with op.batch_alter_table('budget_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_alert_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_alert_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_alert_user_id'))
        batch_op.drop_index(batch_op.f('ix_budget_alert_budget_id'))

    op.drop_table('budget_alert')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_user_id'))

    op.drop_table('budget')
    # ### end Alembic commands ###
