"""add_card_limits_alerts_and_credit_card_fk

Revision ID: 663e62c216eb
Revises: 6ced7844f45c
Create Date: 2026-07-20 18:59:16.171028

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "663e62c216eb"
down_revision: Union[str, Sequence[str], None] = "6ced7844f45c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_spending_limit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credit_card_id", sa.UUID(), nullable=False),
        sa.Column("limit_type", sa.String(length=20), nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column(
            "spent_amount", sa.Numeric(precision=19, scale=4), server_default="0", nullable=False
        ),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_threshold", sa.Integer(), nullable=False),
        sa.Column("alert_enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_card_spending_limit_category_id_category"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["credit_card_id"],
            ["credit_card.id"],
            name=op.f("fk_card_spending_limit_credit_card_id_credit_card"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_card_spending_limit_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_spending_limit")),
    )
    with op.batch_alter_table("card_spending_limit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_card_spending_limit_credit_card_id"), ["credit_card_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_card_spending_limit_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "card_alert",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credit_card_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("threshold_percentage", sa.Integer(), nullable=True),
        sa.Column("current_amount", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("limit_amount", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("credit_card_bill_id", sa.UUID(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["credit_card_bill_id"],
            ["credit_card_bill.id"],
            name=op.f("fk_card_alert_credit_card_bill_id_credit_card_bill"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["credit_card_id"],
            ["credit_card.id"],
            name=op.f("fk_card_alert_credit_card_id_credit_card"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_card_alert_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_alert")),
    )
    with op.batch_alter_table("card_alert", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_card_alert_credit_card_id"), ["credit_card_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_card_alert_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credit_card_id", sa.UUID(), nullable=True))
        batch_op.create_index("ix_transaction_credit_card", ["credit_card_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_transaction_credit_card_id_credit_card"),
            "credit_card",
            ["credit_card_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_transaction_credit_card_id_credit_card"), type_="foreignkey"
        )
        batch_op.drop_index("ix_transaction_credit_card")
        batch_op.drop_column("credit_card_id")

    with op.batch_alter_table("card_alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_alert_user_id"))
        batch_op.drop_index(batch_op.f("ix_card_alert_credit_card_id"))

    op.drop_table("card_alert")
    with op.batch_alter_table("card_spending_limit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_spending_limit_user_id"))
        batch_op.drop_index(batch_op.f("ix_card_spending_limit_credit_card_id"))

    op.drop_table("card_spending_limit")
    # ### end Alembic commands ###
