"""add_financial_goals_tables

Revision ID: 6ced7844f45c
Revises: 5fbda53170bf
Create Date: 2026-07-20 15:09:12.661205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ced7844f45c'
down_revision: Union[str, Sequence[str], None] = '5fbda53170bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_goal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('auto_contribute', sa.Boolean(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('compound_frequency', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('predicted_completion_date', sa.Date(), nullable=True),
    sa.Column('predicted_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommended_monthly', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('prediction_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('milestone_reached_pct', sa.Integer(), nullable=False),
    sa.Column('adjustment_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_financial_goal_account_id_financial_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_financial_goal_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_financial_goal_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_goal'))
    )
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_goal_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_financial_goal_user_status', ['user_id', 'status'], unique=False)

    op.create_table('goal_simulation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('lump_sum', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('lump_sum_date', sa.Date(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('increase_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_completion_date', sa.Date(), nullable=True),
    sa.Column('predicted_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_contributions', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('total_interest', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('months_to_complete', sa.Integer(), nullable=True),
    sa.Column('projection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goal.id'], name=op.f('fk_goal_simulation_goal_id_financial_goal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_goal_simulation_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_simulation'))
    )
    with op.batch_alter_table('goal_simulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_simulation_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_simulation_user_id'), ['user_id'], unique=False)

    op.create_table('goal_milestone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('amount_at_event', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('pct_complete', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goal.id'], name=op.f('fk_goal_milestone_goal_id_financial_goal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_goal_milestone_transaction_id_transaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_goal_milestone_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_milestone'))
    )
    with op.batch_alter_table('goal_milestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_milestone_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_milestone_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_milestone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_milestone_user_id'))
        batch_op.drop_index(batch_op.f('ix_goal_milestone_goal_id'))

    op.drop_table('goal_milestone')
    with op.batch_alter_table('goal_simulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_simulation_user_id'))
        batch_op.drop_index(batch_op.f('ix_goal_simulation_goal_id'))

    op.drop_table('goal_simulation')
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_goal_user_status')
        batch_op.drop_index(batch_op.f('ix_financial_goal_user_id'))

    op.drop_table('financial_goal')
    # ### end Alembic commands ###
