"""add cascade delete to notifications

Revision ID: 739674bb3188
Revises: b1c2d3e4f5g7
Create Date: 2026-07-30 09:21:49.196058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "739674bb3188"
down_revision: Union[str, Sequence[str], None] = "b1c2d3e4f5g7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_notification_user_id_user"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_user_id_user"),
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("notification_preference", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_notification_preference_user_id_user"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_preference_user_id_user"),
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("telegram_link_code", schema=None) as batch_op:
        batch_op.alter_column(
            "is_used",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("telegram_link_code", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "is_used",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("false"),
        )

    with op.batch_alter_table("notification_preference", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_notification_preference_user_id_user"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_preference_user_id_user"), "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_notification_user_id_user"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_notification_user_id_user"), "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
