"""add idempotency login_attempt and transaction version

Revision ID: 76433162681b
Revises: 474bab2c95dc
Create Date: 2026-08-01 09:55:45.729834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76433162681b"
down_revision: Union[str, Sequence[str], None] = "474bab2c95dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempt")),
    )
    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempt_attempted_at"), ["attempted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempt_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.Integer(), server_default="1", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_column("version")

    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempt_user_id"))
        batch_op.drop_index(batch_op.f("ix_login_attempt_attempted_at"))

    op.drop_table("login_attempt")
    # ### end Alembic commands ###
