"""add: processing_started_at to transaction_recurring

Revision ID: 7c8be4bb3e6e
Revises: 9c6d7e8f0a1b
Create Date: 2026-08-06 08:59:43.519180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c8be4bb3e6e'
down_revision: Union[str, Sequence[str], None] = '9c6d7e8f0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_idempotency_keys_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=True)

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_plaid_item_item_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_plaid_item_item_id'))
        batch_op.create_index(batch_op.f('ix_plaid_item_item_id'), ['item_id'], unique=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False,
               existing_server_default=sa.Computed("to_tsvector('spanish'::regconfig, ((COALESCE(description, ''::text) || ' '::text) || COALESCE(notes, ''::text)))", persisted=True))
        batch_op.drop_index(batch_op.f('ix_transaction_search_vector'), postgresql_using='gin')

    with op.batch_alter_table('transaction_recurring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_recurring', schema=None) as batch_op:
        batch_op.drop_column('processing_started_at')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_search_vector'), ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.alter_column('search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True,
               existing_server_default=sa.Computed("to_tsvector('spanish'::regconfig, ((COALESCE(description, ''::text) || ' '::text) || COALESCE(notes, ''::text)))", persisted=True))

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_item_item_id'))
        batch_op.create_index(batch_op.f('ix_plaid_item_item_id'), ['item_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_plaid_item_item_id'), ['item_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.create_unique_constraint(batch_op.f('uq_idempotency_keys_key'), ['key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
