"""add missing multi-currency columns to credit_card

Revision ID: a36b91216e71
Revises: b2c3d4e5f6a7
Create Date: 2026-07-27 09:51:53.834123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a36b91216e71"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("debit_card", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debit_card_account_id"))
        batch_op.drop_index(batch_op.f("ix_debit_card_user_id"))

    op.drop_table("debit_card")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'credit_card' AND column_name = 'is_multicurrency'
            ) THEN
                ALTER TABLE credit_card ADD COLUMN is_multicurrency BOOLEAN;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'credit_card' AND column_name = 'secondary_currency_code'
            ) THEN
                ALTER TABLE credit_card ADD COLUMN secondary_currency_code VARCHAR(3);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'credit_card' AND column_name = 'secondary_credit_limit'
            ) THEN
                ALTER TABLE credit_card ADD COLUMN secondary_credit_limit NUMERIC(19, 4);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'credit_card' AND column_name = 'secondary_available_credit'
            ) THEN
                ALTER TABLE credit_card ADD COLUMN secondary_available_credit NUMERIC(19, 4);
            END IF;
        END $$;
    """)

    op.execute("UPDATE credit_card SET is_multicurrency = false WHERE is_multicurrency IS NULL")

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'credit_card' AND column_name = 'is_multicurrency'
                    AND is_nullable = 'YES'
            ) THEN
                ALTER TABLE credit_card ALTER COLUMN is_multicurrency SET NOT NULL;
            END IF;
        END $$;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_card", schema=None) as batch_op:
        batch_op.drop_column("secondary_available_credit")
        batch_op.drop_column("secondary_credit_limit")
        batch_op.drop_column("secondary_currency_code")
        batch_op.drop_column("is_multicurrency")

    op.create_table(
        "debit_card",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("last_four_digits", sa.VARCHAR(length=4), autoincrement=False, nullable=True),
        sa.Column("card_network", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("color", sa.VARCHAR(length=7), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["financial_account.id"],
            name=op.f("fk_debit_card_account_id_financial_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_debit_card_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debit_card")),
    )
    with op.batch_alter_table("debit_card", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_debit_card_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_debit_card_account_id"), ["account_id"], unique=False)

    # ### end Alembic commands ###
