"""add_transactions

Revision ID: a67553199485
Revises: f19c7a0fa9cf
Create Date: 2026-07-19 19:06:37.058815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a67553199485'
down_revision: Union[str, Sequence[str], None] = 'f19c7a0fa9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_recurring',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_execution_date', sa.Date(), nullable=False),
    sa.Column('max_executions', sa.Integer(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_transaction_recurring_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_recurring_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], name=op.f('fk_transaction_recurring_subcategory_id_subcategory'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_recurring_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_recurring'))
    )
    with op.batch_alter_table('transaction_recurring', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_recurring_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('recurring_id', sa.UUID(), nullable=True),
    sa.Column('ai_category_id', sa.UUID(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_transaction_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ai_category_id'], ['category.id'], name=op.f('fk_transaction_ai_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_id'], ['transaction_recurring.id'], name=op.f('fk_transaction_recurring_id_transaction_recurring'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], name=op.f('fk_transaction_subcategory_id_subcategory'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index('ix_transaction_transfer_id', ['transfer_id'], unique=False)
        batch_op.create_index('ix_transaction_user_effective', ['user_id', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_transaction_user_type', ['user_id', 'transaction_type'], unique=False)

    op.create_table('transaction_attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transaction_attachment_transaction_id_transaction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_attachment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_attachment'))
    )
    with op.batch_alter_table('transaction_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_attachment_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_attachment_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transaction_audit_log_transaction_id_transaction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_audit_log_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_audit_log'))
    )
    with op.batch_alter_table('transaction_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_audit_log_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transaction_tag_transaction_id_transaction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_tag_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_tag')),
    sa.UniqueConstraint('transaction_id', 'tag_name', name='uq_transaction_tag')
    )
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_tag_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_tag_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_tag_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_tag_transaction_id'))

    op.drop_table('transaction_tag')
    with op.batch_alter_table('transaction_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_audit_log_transaction_id'))

    op.drop_table('transaction_audit_log')
    with op.batch_alter_table('transaction_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_attachment_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_attachment_transaction_id'))

    op.drop_table('transaction_attachment')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_user_type')
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index('ix_transaction_user_effective')
        batch_op.drop_index('ix_transaction_transfer_id')
        batch_op.drop_index(batch_op.f('ix_transaction_effective_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('transaction_recurring', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_recurring_user_id'))

    op.drop_table('transaction_recurring')
    # ### end Alembic commands ###
