"""add_wallets

Revision ID: b80f52834e0c
Revises: c3b3599f1acd
Create Date: 2026-07-19 17:51:05.281534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80f52834e0c'
down_revision: Union[str, Sequence[str], None] = 'c3b3599f1acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any orphaned ENUM types
    op.execute("DROP TYPE IF EXISTS wallet_type CASCADE")
    op.execute("DROP TYPE IF EXISTS wallet_status CASCADE")

    op.create_table('wallet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wallet_type', sa.Enum('personal', 'business', 'savings', 'investment', 'daily', 'emergency', name='wallet_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='wallet_status'), server_default='active', nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_wallet_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet'))
    )
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_wallet_account_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('fk_wallet_account_wallet_id_wallet'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_account'))
    )
    with op.batch_alter_table('wallet_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_account_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_account_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_account_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_account_account_id'))

    op.drop_table('wallet_account')
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_user_id'))

    op.drop_table('wallet')
    # ### end Alembic commands ###
