"""much changes

Revision ID: ba861e72087b
Revises: f66325bff6f1
Create Date: 2026-07-28 15:41:30.088150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba861e72087b"
down_revision: Union[str, Sequence[str], None] = "f66325bff6f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("income_source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pay_month", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("pay_weekday", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("income_source", schema=None) as batch_op:
        batch_op.drop_column("pay_weekday")
        batch_op.drop_column("pay_month")

    # ### end Alembic commands ###
