"""add_tax_tables

Revision ID: c1d2e3f4a5b6
Revises: b0c1d2e3f4a5
Create Date: 2026-08-02 11:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1d2e3f4a5b6"
down_revision: str | None = "b0c1d2e3f4a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_tax_category_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_category")),
    )
    with op.batch_alter_table("tax_category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tax_category_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_tax_category_user_year", ["user_id", "tax_year"], unique=False)

    op.create_table(
        "tax_deduction",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("deductible", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("receipt_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["tax_category.id"],
            name=op.f("fk_tax_deduction_category_id_tax_category"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_tax_deduction_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_deduction")),
    )
    with op.batch_alter_table("tax_deduction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tax_deduction_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tax_deduction_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_tax_deduction_user_year", ["user_id", "tax_year"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tax_deduction", schema=None) as batch_op:
        batch_op.drop_index("ix_tax_deduction_user_year")
        batch_op.drop_index(batch_op.f("ix_tax_deduction_user_id"))
        batch_op.drop_index(batch_op.f("ix_tax_deduction_category_id"))

    op.drop_table("tax_deduction")
    with op.batch_alter_table("tax_category", schema=None) as batch_op:
        batch_op.drop_index("ix_tax_category_user_year")
        batch_op.drop_index(batch_op.f("ix_tax_category_user_id"))

    op.drop_table("tax_category")
    # ### end Alembic commands ###
