"""add_financial_accounts

Revision ID: c3b3599f1acd
Revises: 28e8f29983b9
Create Date: 2026-07-19 17:15:04.439770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b3599f1acd'
down_revision: Union[str, Sequence[str], None] = '28e8f29983b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('bank', 'cash', 'savings', 'checking', 'wallet', 'crypto', name='account_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', 'frozen', name='account_status'), server_default='active', nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('account_number_last4', sa.String(length=4), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('include_in_net_worth', sa.Boolean(), nullable=False),
    sa.Column('include_in_totals', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_financial_account_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_account'))
    )
    with op.batch_alter_table('financial_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_account_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_account_user_id'))

    op.drop_table('financial_account')
    # ### end Alembic commands ###
