"""add_insurance_tables

Revision ID: d2e3f4a5b6c7
Revises: c1d2e3f4a5b6
Create Date: 2026-08-02 11:05:30.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2e3f4a5b6c7"
down_revision: str | None = "c1d2e3f4a5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "life",
                "health",
                "auto",
                "home",
                "travel",
                "disability",
                "other",
                name="insurance_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", "expired", "pending", name="insurance_status_enum"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("coverage_amount", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("premium_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column(
            "premium_frequency",
            sa.Enum("monthly", "quarterly", "semi_annual", "annual", name="premium_frequency_enum"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_insurance_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance")),
    )
    with op.batch_alter_table("insurance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insurance_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_insurance_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "insurance_policy",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insurance_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("coverage_details", sa.Text(), nullable=True),
        sa.Column("deductible", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["insurance_id"],
            ["insurance.id"],
            name=op.f("fk_insurance_policy_insurance_id_insurance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_policy")),
    )
    with op.batch_alter_table("insurance_policy", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_insurance_policy_insurance_id"), ["insurance_id"], unique=False
        )

    op.create_table(
        "insurance_premium",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insurance_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "overdue", "cancelled", name="premium_status_enum"),
            nullable=False,
        ),
        sa.Column("payment_method", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["insurance_id"],
            ["insurance.id"],
            name=op.f("fk_insurance_premium_insurance_id_insurance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_premium")),
    )
    with op.batch_alter_table("insurance_premium", schema=None) as batch_op:
        batch_op.create_index(
            "ix_insurance_premium_due_date", ["insurance_id", "due_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_insurance_premium_insurance_id"), ["insurance_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurance_premium", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_premium_insurance_id"))
        batch_op.drop_index("ix_insurance_premium_due_date")

    op.drop_table("insurance_premium")
    with op.batch_alter_table("insurance_policy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_policy_insurance_id"))

    op.drop_table("insurance_policy")
    with op.batch_alter_table("insurance", schema=None) as batch_op:
        batch_op.drop_index("ix_insurance_user_status")
        batch_op.drop_index(batch_op.f("ix_insurance_user_id"))

    op.drop_table("insurance")
    # ### end Alembic commands ###
