"""add_categories

Revision ID: f19c7a0fa9cf
Revises: b80f52834e0c
Create Date: 2026-07-19 18:14:08.647813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19c7a0fa9cf'
down_revision: Union[str, Sequence[str], None] = 'b80f52834e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_category_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_user_id'), ['user_id'], unique=False)

    op.create_table('subcategory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_subcategory_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcategory'))
    )
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategory_category_id'), ['category_id'], unique=False)

    op.create_table('category_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern_type', sa.String(length=30), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('target_category_id', sa.UUID(), nullable=False),
    sa.Column('target_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_category_id'], ['category.id'], name=op.f('fk_category_rule_target_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_subcategory_id'], ['subcategory.id'], name=op.f('fk_category_rule_target_subcategory_id_subcategory'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_category_rule_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_rule'))
    )
    with op.batch_alter_table('category_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rule_target_category_id'), ['target_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_rule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_rule_target_category_id'))

    op.drop_table('category_rule')
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategory_category_id'))

    op.drop_table('subcategory')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_user_id'))

    op.drop_table('category')
    # ### end Alembic commands ###
