"""add_investment_tables

Revision ID: f1a2b3c4d5e6
Revises: e3f4a5b6c7d8
Create Date: 2026-08-03 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: str | None = "e3f4a5b6c7d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "stock",
                "bond",
                "etf",
                "crypto",
                "mutual_fund",
                "real_estate",
                "commodity",
                name="asset_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_assets_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_asset_user_type", ["user_id", "asset_type"], unique=False)

    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_portfolios_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_portfolios_user_id"), ["user_id"], unique=False)

    op.create_table(
        "portfolio_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=19, scale=8), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_portfolio_assets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_assets_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_assets")),
        sa.UniqueConstraint("portfolio_id", "asset_id", name="uq_portfolio_assets_portfolio_asset"),
    )
    with op.batch_alter_table("portfolio_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_assets_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_portfolio_assets_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "investment_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("buy", "sell", "dividend", "fee", name="investment_tx_type_enum"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=19, scale=8), nullable=False),
        sa.Column("price_per_unit", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("fees", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_investment_transactions_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_investment_transactions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investment_transactions")),
    )
    with op.batch_alter_table("investment_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_investment_transactions_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_investment_transactions_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index("ix_investment_tx_asset_date", ["asset_id", "date"], unique=False)

    op.create_table(
        "asset_price_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("high_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("volume", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_price_history_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_price_history")),
        sa.UniqueConstraint("asset_id", "date", name="uq_asset_price_history_asset_date"),
    )
    with op.batch_alter_table("asset_price_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_price_history_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            "ix_asset_price_history_asset_date", ["asset_id", "date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset_price_history", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_price_history_asset_date")
        batch_op.drop_index(batch_op.f("ix_asset_price_history_asset_id"))

    op.drop_table("asset_price_history")
    with op.batch_alter_table("investment_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_investment_tx_asset_date")
        batch_op.drop_index(batch_op.f("ix_investment_transactions_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_investment_transactions_asset_id"))

    op.drop_table("investment_transactions")
    with op.batch_alter_table("portfolio_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_assets_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_portfolio_assets_asset_id"))

    op.drop_table("portfolio_assets")
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolios_user_id"))

    op.drop_table("portfolios")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_user_type")
        batch_op.drop_index(batch_op.f("ix_assets_user_id"))
        batch_op.drop_index(batch_op.f("ix_assets_symbol"))

    op.drop_table("assets")
    # ### end Alembic commands ###
