"""restore debit_card table

Revision ID: f66325bff6f1
Revises: a36b91216e71
Create Date: 2026-07-27 09:57:36.668332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66325bff6f1'
down_revision: Union[str, Sequence[str], None] = 'a36b91216e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True),
    sa.Column('card_network', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], name=op.f('fk_debit_card_account_id_financial_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_debit_card_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debit_card'))
    )
    with op.batch_alter_table('debit_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debit_card_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_card_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_card_user_id'))
        batch_op.drop_index(batch_op.f('ix_debit_card_account_id'))

    op.drop_table('debit_card')
    # ### end Alembic commands ###
