"""add_notification_tables

Revision ID: ffb27bee88cf
Revises: 56f13aaab89f
Create Date: 2026-07-21 14:32:10.511117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb27bee88cf'
down_revision: Union[str, Sequence[str], None] = '56f13aaab89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notification_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_notification_user_channel', ['user_id', 'channel'], unique=False)
        batch_op.create_index('ix_notification_user_id', ['user_id'], unique=False)

    op.create_table('notification_preference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('push_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discord_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('discord_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_preference_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preference_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_id')
        batch_op.drop_index('ix_notification_user_channel')
        batch_op.drop_index('ix_notification_is_read')
        batch_op.drop_index('ix_notification_created_at')

    op.drop_table('notification')
    # ### end Alembic commands ###
